/**
 * WOARU Multi-LLM AI Code Review Configuration
 * Generated by woaru setup llm
 */

module.exports = {
  "ai": {
    "providers": [
      {
        "id": "anthropic-claude",
        "providerType": "anthropic",
        "apiKeyEnvVar": "ANTHROPIC_API_KEY",
        "baseUrl": "https://api.anthropic.com/v1/messages",
        "model": "claude-3-5-sonnet-20241022",
        "headers": {
          "anthropic-version": "2023-06-01"
        },
        "bodyTemplate": "{\"model\":\"{model}\",\"max_tokens\":4000,\"temperature\":0.1,\"messages\":[{\"role\":\"user\",\"content\":\"{prompt}\\n\\nCode to analyze:\\n```{language}\\n{code}\\n```\"}]}",
        "timeout": 30000,
        "maxTokens": 4000,
        "temperature": 0.1,
        "enabled": true
      },
      {
        "id": "openai-gpt4",
        "providerType": "openai",
        "apiKeyEnvVar": "OPENAI_API_KEY",
        "baseUrl": "https://api.openai.com/v1/chat/completions",
        "model": "gpt-4o",
        "headers": {},
        "bodyTemplate": "{\"model\":\"{model}\",\"messages\":[{\"role\":\"system\",\"content\":\"{systemPrompt}\"},{\"role\":\"user\",\"content\":\"{prompt}\\n\\nCode to analyze:\\n```{language}\\n{code}\\n```\"}],\"max_tokens\":4000,\"temperature\":0.1}",
        "timeout": 30000,
        "maxTokens": 4000,
        "temperature": 0.1,
        "enabled": true
      }
    ],
    "parallelRequests": true,
    "consensusMode": false,
    "minConsensusCount": 2,
    "tokenLimit": 8000,
    "costThreshold": 0.50
  }
};